### ISSUE TITLE
Sentinel-1 data (Ghana monthly mean) don't show full extent

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#123] opened 2020-04-29 04:51 UTC
The Sentinel-1 monthly means over Ghana, which are available at `s3://deafrica-data/esa/s1/ghana-s1/` don't correctly display full extents, but do show when you limit time to a specific month or dataset.

Steps to index are:
- Create fresh database
- Add the product `datacube product add https://raw.githubusercontent.com/digitalearthafrica/config/master/products/sentinel1_ghana_monthly.yaml`
- Add the data: `s3-find "s3://deafrica-data/esa/s1/ghana-s1/**/**/**/**/**/*.yaml" | s3-to-tar | dc-index-from-tar`
- View the data on the Explorer page, see image below

![image](https://user-images.githubusercontent.com/3445853/80561682-96b52400-8a28-11ea-86e1-ebbf569b39a5.png)

**Comment by pindge** [comment] 2022-07-12 05:03
Closing as cannot reproduce with the instruction provided.

**Closed as completed by pindge** 2022-07-12 05:03 UTC
Labels: bug
