### ISSUE TITLE
product-audit page fails on africa instance

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-explorer#73] opened 2020-01-21 05:18 UTC
https://explorer.digitalearth.africa/product-audit/

"Internal error"

@santoshamohan provided the following log from the server:
```
[2020-01-21 05:03:24,771] ERROR in app: Exception on /product-audit/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/code/cubedash/_audit.py", line 81, in product_audit_page
    spatial_quality_stats=list(store.get_quality_stats()),
  File "/code/cubedash/summary/_stores.py", line 341, in get_quality_stats
    d["product"] = self._dataset_type_by_id(row["dataset_type_ref"])
  File "/code/cubedash/summary/_stores.py", line 301, in _dataset_type_by_id
    raise KeyError("Unknown dataset type id %r" % id_)
KeyError: 'Unknown dataset type id 18'
```

**Comment by omad** [comment] 2020-02-26 05:57
Having trouble reproducing locally, running latest datacube-core `develop` and datacube-explorer `develop`, and the latest DB dump from deafrica.

It looks like a data error inside the database, so will need more looking into.

**Comment by jeremyh** [comment] 2020-02-26 05:59
It could have happened if any products were deleted from odc but still in explorer tables. Or any related weirdness from dropping one schema but not the other.

**Comment by omad** [comment] 2020-02-26 22:52
Seems to be fixed in the latest code, closing.

**Closed as completed by omad** 2020-02-26 22:52 UTC
